#!/usr/bin/env python3
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = Path('/usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-Medium.ttf')
OUT_H = ROOT / 'waveshare_c6_clock' / 'clock_font.h'
PREVIEW = ROOT / 'waveshare_c6_clock' / 'jetbrains_clock_preview.png'
CHARS = '0123456789:'
FONT_SIZE = 104
TEXT = '10:20'
UI_W, UI_H = 320, 172

font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)
# Use a shared ascent/descent and monospace advance; crop each glyph to its actual alpha box.
asc, desc = font.getmetrics()
advance = int(round(font.getlength('0')))
line_h = asc + desc

glyphs = []
for ch in CHARS:
    canvas = Image.new('L', (advance + 24, line_h + 24), 0)
    d = ImageDraw.Draw(canvas)
    d.text((12, 12), ch, font=font, fill=255)
    bbox = canvas.getbbox()
    if bbox is None:
        bbox = (0, 0, 1, 1)
    # Keep common height/ascent alignment by using bbox plus offsets from draw origin.
    x0, y0, x1, y1 = bbox
    bitmap = canvas.crop(bbox)
    if ch == '0':
        # JetBrains Mono's zero has a small disconnected center dot.
        # For the clock face, remove small non-border components while keeping
        # the outer zero contour and antialiasing intact.
        px = bitmap.load()
        w0, h0 = bitmap.size
        seen = [[False] * h0 for _ in range(w0)]
        for sy in range(h0):
            for sx in range(w0):
                if seen[sx][sy] or px[sx, sy] == 0:
                    continue
                stack = [(sx, sy)]
                seen[sx][sy] = True
                comp = []
                touches_border = False
                while stack:
                    cx, cy = stack.pop()
                    comp.append((cx, cy))
                    if cx == 0 or cy == 0 or cx == w0 - 1 or cy == h0 - 1:
                        touches_border = True
                    for nx in (cx - 1, cx, cx + 1):
                        for ny in (cy - 1, cy, cy + 1):
                            if nx == cx and ny == cy:
                                continue
                            if 0 <= nx < w0 and 0 <= ny < h0 and not seen[nx][ny] and px[nx, ny] != 0:
                                seen[nx][ny] = True
                                stack.append((nx, ny))
                if not touches_border and len(comp) < 900:
                    for cx, cy in comp:
                        px[cx, cy] = 0
    w, h = bitmap.size
    off_x = x0 - 12
    off_y = y0 - 12
    data = list(bitmap.getdata())
    glyphs.append((ch, w, h, off_x, off_y, advance, data))

# Preview render using same glyph metrics/bitmap composition.
def draw_text(img, x, y, text):
    for ch in text:
        g = next(g for g in glyphs if g[0] == ch)
        _, w, h, ox, oy, adv, data = g
        gm = Image.new('L', (w, h))
        gm.putdata(data)
        white = Image.new('RGB', (w, h), (255, 255, 255))
        img.paste(white, (x + ox, y + oy), gm)
        x += adv

# Compute text bbox for center.
total_w = sum(next(g for g in glyphs if g[0] == ch)[5] for ch in TEXT)
text_h = line_h
px = (UI_W - total_w) // 2
py = (UI_H - text_h) // 2
preview = Image.new('RGB', (UI_W, UI_H), (0, 0, 0))
draw_text(preview, px, py, TEXT)
preview.save(PREVIEW)

lines = []
lines.append('// Generated by tools/generate_clock_font.py from JetBrains Mono Regular. Do not edit by hand.\n')
lines.append('#pragma once\n')
lines.append('#include <Arduino.h>\n')
lines.append('#include <pgmspace.h>\n\n')
lines.append('struct ClockGlyph {\n')
lines.append('  char ch;\n  uint8_t w;\n  uint8_t h;\n  int8_t xOffset;\n  int8_t yOffset;\n  uint8_t advance;\n  const uint8_t* data;\n};\n\n')
for ch, w, h, ox, oy, adv, data in glyphs:
    name = 'colon' if ch == ':' else ch
    lines.append(f'static const uint8_t clock_glyph_{name}[] PROGMEM = {{\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append('  ' + ', '.join(str(v) for v in chunk) + ',\n')
    lines.append('};\n\n')
lines.append(f'static constexpr uint8_t CLOCK_FONT_SIZE = {FONT_SIZE};\n')
lines.append(f'static constexpr uint8_t CLOCK_FONT_ASCENT = {asc};\n')
lines.append(f'static constexpr uint8_t CLOCK_FONT_DESCENT = {desc};\n')
lines.append(f'static constexpr uint8_t CLOCK_FONT_LINE_H = {line_h};\n')
lines.append('static const ClockGlyph CLOCK_GLYPHS[] PROGMEM = {\n')
for ch, w, h, ox, oy, adv, data in glyphs:
    name = 'colon' if ch == ':' else ch
    lines.append(f"  {{'{ch}', {w}, {h}, {ox}, {oy}, {adv}, clock_glyph_{name}}},\n")
lines.append('};\n')
lines.append('static constexpr uint8_t CLOCK_GLYPH_COUNT = sizeof(CLOCK_GLYPHS) / sizeof(CLOCK_GLYPHS[0]);\n')
OUT_H.write_text(''.join(lines))
print(f'wrote {OUT_H}')
print(f'wrote {PREVIEW}')
print(f'font={FONT_PATH} size={FONT_SIZE} ascent={asc} descent={desc} advance={advance} total_w={total_w} py={py}')
for ch, w, h, ox, oy, adv, _ in glyphs:
    print(f'{ch}: {w}x{h} offset=({ox},{oy}) advance={adv}')
